### ISSUE TITLE
Floating TOC is packed when headers have long sentences

### ISSUE THREAD

**Issue by Liong1976** [cumany/obsidian-floating-toc-plugin#10]
First of all, I want to thank you for making this wonderful plugin.

It seems that the TOC is packed (overlapping each other) when headers have long sentences. See the screenshot below.

![image](https://user-images.githubusercontent.com/88898230/191833192-624b521d-246f-4d4d-8917-09b9302dee9d.png)

Thank you

**Comment by cumany** [comment]
fixed

**Comment by Liong1976** [comment]
Thanks, @cumany !

**Comment by Liong1976** [comment]
It looks like the TOC becomes messy. Please see the screenshot. Thanks

![image](https://user-images.githubusercontent.com/88898230/191966880-aca51524-4e68-46e3-9646-ee9e34c8c394.png)

**Comment by Liong1976** [comment]
After restarting, it looks better. But there are some headers that cannot be clicked (the white ones).

![image](https://user-images.githubusercontent.com/88898230/191967471-56783cb2-9f08-4948-87eb-658e49caeb4e.png)

**Comment by Liong1976** [comment]
For longer sentences, the TOC is still overlapping.

![image](https://user-images.githubusercontent.com/88898230/192053435-43ee0dfb-985b-4a3a-8864-70e0c105d74c.png)

**Comment by cumany** [comment]
Version 2.1.2 has been released, try the update

**Comment by DutchPete** [comment]
That has not changed in 2.1.2.

**Comment by cumany** [comment]
Try restarting ob and switching to the default theme? Does it relate to your theme?

**Comment by DutchPete** [comment]
Even with the default theme and disabling my snippets there is no change.

**Comment by cumany** [comment]
Okay, so far the issue you pointed out is, "For longer sentences, the TOC is still overlapping." Is that it? 
Can you post some long titles for me to test?

**Comment by Liong1976** [comment]
It is not overlapping anymore. Thanks, @cumany!

![image](https://user-images.githubusercontent.com/88898230/192123367-07926fe3-557a-4cb9-8b67-9b27e17b05f5.png)

**Comment by DutchPete** [comment]
@Liong1976 what exactly do you mean by overlapping? In your last screenshot the ToC still overlaps the text of the note. Maybe I misunderstand your meaning of “overlap”?

**Comment by Liong1976** [comment]
What I meant with "overlap" is that the headers do not overlap one another, I didn't mean overlap the main text.

**Comment by DutchPete** [comment]
> the headers do not overlap one another

Isn't it supposed to be that way?
