### ISSUE TITLE
标题内链接能否实现预览，要不看起来很丑，谢谢大佬

### ISSUE THREAD

**Issue by shoudeyunkaijianyueming** [cumany/obsidian-floating-toc-plugin#11]
[🚀 ]( marginnote3app://note/6F47996E-80CA-4B4D-99EB-9037DB904D37) 类似于这种
<img width="336" alt="image" src="https://user-images.githubusercontent.com/71814666/191875312-e1748dac-0814-4111-a72d-9a2dfd1c20d1.png">
![截图2022-09-23_09-00](https://user-images.githubusercontent.com/71814666/191875394-a767633b-c11f-4d1f-b5f7-3441392e2290.jpg)

**Comment by cumany** [comment]
更新 已经支持

**Comment by shoudeyunkaijianyueming** [comment]
谢谢
