### ISSUE TITLE
H1 captions are rendered in triplicate & don't change color

### ISSUE THREAD

**Issue by DutchPete** [cumany/obsidian-floating-toc-plugin#17]
![image](https://user-images.githubusercontent.com/10794265/192301642-4a89c29f-a110-448d-aa59-92da3dfff1c9.png)
The screenshot shows that H1 is rendered in triplicate; the other headings are not.
Furthermore, the text color of the H1 is as in the note text, whereas the other headings' colors are rendered properly.

BTW, version 2.1.5 of the plug-in is awesome!!! You did an amazing job there.

**Comment by Liong1976** [comment]
The same here. This happened from the beginning, but I thought my theme caused it.

![image](https://user-images.githubusercontent.com/88898230/192309536-dd56f6bb-12f9-4ac5-baa2-6979f80d1590.png)

**Comment by cumany** [comment]
oh，This is a bug  and 2.1.6 has been fixed

**Comment by DutchPete** [comment]
Version 2.1.6 not coming through on BRAT yet, so I can't comment. I'll wait a bit.

**Comment by DutchPete** [comment]
Got 2.1.6: perfect. Thank you!

**Comment by Liong1976** [comment]
Thanks, @cumany!

**Comment by Liong1976** [comment]
What is the emoticon pin for?

![image](https://user-images.githubusercontent.com/88898230/192336601-ae5b1385-74a0-41b2-81ad-d326c5ca3a66.png)

**Comment by DutchPete** [comment]
I had not noticed it, but after your question, my 1<sup>st</sup> thought was: to pin the Floating ToC so it remains visible. But clicking on it does nothing, it appears.

**Comment by Liong1976** [comment]
Yeah, you are right!
