### ISSUE TITLE
TOC的title不能跟随文本滚动。

### ISSUE THREAD

**Issue by llity** [cumany/obsidian-floating-toc-plugin#18]
1. 添加滚动到哪个heading可以高亮显示选项。
<img width="715" alt="image" src="https://user-images.githubusercontent.com/11771112/192413136-c84ea866-b03c-49f9-88a3-944e9d923a9f.png">

2. 类似sspai网站显示，H2 section，此Heading标签和文本显示，在整个Section内显示，目前发现是顶部出现会促发高亮。
<img width="550" alt="image" src="https://user-images.githubusercontent.com/11771112/192413446-1e9d60ab-15ff-4d24-bad8-1d0aef08909f.png">

3. 右侧pin模式有点bug，被遮挡了
<img width="213" alt="image" src="https://user-images.githubusercontent.com/11771112/192414230-3b89cb7a-a535-4bb0-b863-1aefbe5eadaf.png">
同时发现pin后没显示
<img width="253" alt="image" src="https://user-images.githubusercontent.com/11771112/192418169-cc743b0c-8c8b-4d2e-8c2b-2c680812a98f.png">

<img width="190" alt="image" src="https://user-images.githubusercontent.com/11771112/192418386-dd6f3466-e0db-4e98-b5f7-d05d9af6f94d.png">

4. 鼠标放下面的H2有出不来的bug，而且提示的横线和出来的标题位置没有对齐。
![Sep-27-2022 10-13-33](https://user-images.githubusercontent.com/11771112/192415585-0b4d7bb8-8108-4145-a999-6aa073ee481d.gif)
其他建议。
<img width="609" alt="image" src="https://user-images.githubusercontent.com/11771112/192415904-14177bc3-c9dd-4687-b411-9edcb6a6dd10.png">

谢谢

**Comment by cumany** [comment]
2.1.8 修复了一些问题

**Comment by cumany** [comment]
2.2.2 做了类似sspai的风格设置
