### ISSUE TITLE
发现两个问题

### ISSUE THREAD

**Issue by chenxin0397** [cumany/obsidian-floating-toc-plugin#19]
1. 希望给Pin功能加个快捷键
如果目录太长，加上动画效果可能会使点击专用按钮变得困难，除非能很快又很精准的点到按钮

2. 浮动目录显示位置选择在右边之后，用pin固定且会超出编辑区（看不见）

**Comment by tim-hilde** [comment]
To add on this: Add an option to show/hide the pin in the style settings. I'm currently using a snippet to hide it completely

**Comment by cumany** [comment]
2.1.8  fixed
