### ISSUE TITLE
浮动目录没有对标题中的公式进行解析

### ISSUE THREAD

**Issue by bcdax110** [cumany/obsidian-floating-toc-plugin#2]
文件中的标题：
![image](https://user-images.githubusercontent.com/15951421/190944377-8faa5602-ae7c-492a-ab3a-96b5d3e00556.png)
浮动窗口中的标题：
![image](https://user-images.githubusercontent.com/15951421/190944446-bd13403d-92c2-4ad3-a779-7bc01018577a.png)

**Comment by cumany** [comment]
不仅仅是公式，目前标题的文字都没有md渲染，也就是都是源码方式输出的。这个设计md解析之类，后面看情况能否实现这个特性。

**Comment by cumany** [comment]
新版本 已发布，已支持此特性
