### ISSUE TITLE
Note text blur

### ISSUE THREAD

**Issue by javiavid** [cumany/obsidian-floating-toc-plugin#21]
When you have narrow panels the toc and document text get mixed up and look a bit off.
I don't know if it's possible, but it would be interesting an option so that the text of the note fades when activating the toc.

![image](https://user-images.githubusercontent.com/7627504/193222522-57be9afd-0ca8-49b4-a1a3-b49c92d43b43.png)

![image](https://user-images.githubusercontent.com/7627504/193224937-2e29576b-8e3e-401a-a22b-d533be0e2ed7.png)

**Comment by cumany** [comment]
2.2.0 supports relevant settings in style setting.

![image](https://user-images.githubusercontent.com/42957010/193460249-5053acff-d1a2-4dcc-87a4-1686f189e7c5.png)

**Comment by javiavid** [comment]
Thanks!

**Comment by DutchPete** [comment]
I don't have this option in Style Settings, even though both Floating TOC and SS are up-to-date.

**Comment by cumany** [comment]
> I don't have this option in Style Settings, even though both Floating TOC and SS are up-to-date.

Try closing the style setting plugin and reopening it.

**Comment by DutchPete** [comment]
Did that: still does not work.

**Comment by cumany** [comment]
> Did that: still does not work. I also relaunched Obsidian.
> 
> Update: I decided to unistall Style Settings, then reinstall. The blur option still does not appear. 😢

please notice #20

If the name of your plugin is obsidian-floating-toc you need to uninstall and reinstall the new version for it to work properly.

**Comment by DutchPete** [comment]
OK, that was the problem. The Style Settings show it. BTW, #20 is in Chinese so I don't know what it was about.

Anyway, the Floating ToC does not show in the left anymore!! I relaunched Obsidian, no luck. Should I open another issue?

**Comment by cumany** [comment]
> OK, that was the problem. The Style Settings show the blur option now. BTW, #20 is in Chinese so I don't know what it was about.
> 
> Anyway, the Floating ToC does not show in the left anymore!! I relaunched Obsidian, no luck. Should I open another issue?

As shown in the picture, you can choose the location in the plugin settings
![image](https://user-images.githubusercontent.com/42957010/193565675-2d8ddff2-f9d1-41f0-a9f3-67036b595f1b.png)

**Comment by DutchPete** [comment]
I know, I kept your default setting as per the screenshot.
I also tried changing it to “right” and back to “left”: no luck. The FT does not appear at all.

**Comment by DutchPete** [comment]
Solved, mysteriously. It works now, blur included. Thank a lot!
