### ISSUE TITLE
开启插件后滚动长文章到顶时主界面位置异常

### ISSUE THREAD

**Issue by lanx214** [cumany/obsidian-floating-toc-plugin#22]
- 操作系统：win10
- 主程序版本：v0.15.9
- 插件版本：2.1.9
- 问题：
    - 打开插件后，长文章向上滑动到顶时，主界面会异常向上移动（如图）；关闭插件后正常；重启插件，重启主程序均无法解决。
    - ![New_New_New_tmp6E50](https://user-images.githubusercontent.com/52954312/193436994-b984982a-8fb4-485a-8ec1-cbe7cb9bfbab.png) ![New_New_tmpE1FB](https://user-images.githubusercontent.com/52954312/193436995-355f0990-2896-452b-9dfe-00bec9c0f92f.png)

另：请问是否能单独选择在移动端关闭插件？如果在插件开关处关闭插件，同步到桌面端时插件也会关闭。是否有办法能在桌面端开启插件并使用，而移动端关闭？谢谢~

**Comment by cumany** [comment]
2.2.0 修复了
