### ISSUE TITLE
该插件是否没有为Obsidian1.0版本做适配呢？是否有计划为1.0做适配？

### ISSUE THREAD

**Issue by jokechen102** [cumany/obsidian-floating-toc-plugin#28]
我在obsidian1.0中使用时，发现悬浮的大纲与横线并不能对齐，强迫症患者非常难受～

![iShot_2022-10-25_16 01 43](https://user-images.githubusercontent.com/79050867/197717681-c02dfa42-cf34-4cbb-920e-03ab0ad1db8f.png)
![iShot_2022-10-25_16 01 32](https://user-images.githubusercontent.com/79050867/197717702-be14625b-1a90-49f8-a5f9-10217e0f1637.png)

**Comment by cumany** [comment]
这边 1.0 版本使用正常 无法复现你的问题，建议你用新库 开启插件测试是否有问题
