### ISSUE TITLE
Support hiding Level 1 heading

### ISSUE THREAD

**Issue by wenlzhang** [cumany/obsidian-floating-toc-plugin#3]
I often have level 1 heading like `# Title` in most notes. Therefore, it would be great if one can choose to disable such level 1 heading in floating TOC.

**Comment by wenlzhang** [comment]
It would be even better if it can neglect heading in the following manner. This plugin would detect the highest level of headers within a note; if there is only one highest-level header, then this header would be neglected. For example, in the following notes, Level 1 and Level 3 headings would be neglected, respectively.

Note A:
```
# Heading Level 1

XX.

## Heading Level 2

XX.

## Heading Level 2

XX.
```

Note B:
```
### Heading Level 1

XX.

#### Heading Level 2

XX.

#### Heading Level 2

XX.
```

**Comment by cumany** [comment]
2.2.2 Added this option to hide the top-level header
