### ISSUE TITLE
ctrl + click to collapse/expand the header doesnt work on mac

### ISSUE THREAD

**Issue by tim-hilde** [cumany/obsidian-floating-toc-plugin#30]
ctrl + click to collapse/expand the header doesnt work on mac

**Comment by cumany** [comment]
try command +click  on a mac

**Comment by tim-hilde** [comment]
Thats what I tried, but it doesnt work

**Comment by cumany** [comment]
New version updated, try the cmd +click if it works.

**Comment by tim-hilde** [comment]
Yes, that works, though I just realized I thought of the feature as something different. Namely, to expand/collapse the header inside the floating toc. That would also be a nice feature to add.
