### ISSUE TITLE
Feature Request: Adjusting indentation level

### ISSUE THREAD

**Issue by nhan000** [cumany/obsidian-floating-toc-plugin#31]
Hi, _amazing_ plugin that addresses a burning need when I moved from Logseq. Can't say how grateful I am and how beautiful and customizable the interface is. Thank you so so much!

My feature request is if you could add a setting in Style Setting plugin that allows increasing the indentation between heading levels. Currently it's a bit hard to discern different heading levels, especially when the TOC gets complicated with various levels.

![image](https://user-images.githubusercontent.com/85216095/201013835-05844ac8-3fd0-46e0-ad69-334e69af8ad7.png)

**Comment by DutchPete** [comment]
@nhan000  If you have the headings numbered it is a lot easier; there is a plug-in for that.

**Comment by cumany** [comment]
In fact, each heading is followed by a serial number to discern different heading levels

**Comment by nhan000** [comment]
I guess you're talking about [Number Headings Plugin](https://github.com/onlyafly/number-headings-obsidian).

The issue with this is that if you have internal links to the heading, that link will break when you rename the heading using the plugin, because Obsidian doesn't update links to headings like how it updates links when you change the name of a note. [Automatic/inline update of links to headers and blocks when they are modified (no extra dialog window) - Feature requests - Obsidian Forum](https://forum.obsidian.md/t/automatic-inline-update-of-links-to-headers-and-blocks-when-they-are-modified-no-extra-dialog-window/25412/16)

**Comment by DutchPete** [comment]
@nhan000 yes, that is the plug-in I referred to. Internal links to headings are broken because the plug-in actually adds the numbers to the heading. I spoke to the dev about this, asking if he could not make the numbers virtual, like in Typora, but he said he could not, it would require a different plug-in.

There is such a plug-in being developed: *Numbered headings* by Platon Ivanov. It is not in the community repository yet. I have not heard about it for a while.

The issue with that one is that, because the numbers are virtual, *Floating ToC* will not detect them. I don't know if that will be an issue for @cumany or for Platon Ivanov.

**Comment by DutchPete** [comment]
@nhan000 I found the [forum thread](https://forum.obsidian.md/t/header-counter/3525/69).

**Comment by nhan000** [comment]
@DutchPete Yeah I'm aware of the issue, and even Erica has chimed in and said that Obsidian won't auto update link to headings unless you right-click and choose the `Rename Heading` command because it will severely affects the performance, so I think that will cause some difficulty for onlyafly with [Number Headings Plugin](https://github.com/onlyafly/number-headings-obsidian) if he ever wants to make Obsidian update links to headings. 

And even if the [Obsidian Heading plugin](https://github.com/platon-ivanov/obsidian-heading-counter) from Platon Ivanov works, the number won't appear in the Floating TOC plugin because it's only added visually, so I think my feature request is still valid.

**Comment by DutchPete** [comment]
@nhan000 of course your FR is still valid, my comment was just meant to show alternatives.

I agree onlyfly's plug-in will be obsolete if Platon Ivanov's plug-in makes it; I just sent him an email to ask if there is any news. The fact that his plug-in only adds a virtual number now does not mean that it is not possible to make it detectable by Floating ToC.

Like I said, the heading numbers in Typora are only visual too, and yet its outline is able to detect and show them! So, at this stage I am hopeful Platon's plug-in and Floating ToC will be able to work as a “team”.

**Comment by cumany** [comment]
This feature request, as I understand it, means adding an option to adjust the indent value of the head.
Just reading your discussion, it seems to revolve around whether or not you should add head  level number, this might be another issue

**Comment by DutchPete** [comment]
@cumany to be fair, it is I who mentioned numbering, whereas @nhan000 only asked for indentation.

The request was made to be able to better distinguish various header types from one another. Numbering would be 1 way of doing it, but it has drawbacks, so from @nhan000's point of view it is not an option.

**Comment by cumany** [comment]
2.3.0 already supports header hierarchy line display and custom header colors
