### ISSUE TITLE
打开不包含任何标题的文档时会显示上一个文档的大纲

### ISSUE THREAD

**Issue by lanx214** [cumany/obsidian-floating-toc-plugin#33]
操作系统：win10
主程序版本：v1.0.3
插件版本：2.2.5
问题：先打开一个包含大纲的文档之后，再转到另一个无任何标题的文档时，会显示上一个文档的大纲。

**Comment by cumany** [comment]
可否录屏说明 因为这个bug 我没办法复现

**Comment by lanx214** [comment]
https://user-images.githubusercontent.com/52954312/201513588-a3c5deaf-304a-42c5-a966-0f19d8128977.mp4

不知道这样是否清楚。过程包含了两个文档“测试”和“测试1”。其中测试里包含大纲，测试1为空文档。
录屏包含的操作：软件启动后默认打开“测试”时，正常不显示toc；点击打开“测试1”，正常显示测试1的toc；点击打开“测试”，仍然显示“测试1”的toc。

**Comment by cumany** [comment]
文档切换你用快捷键 还是鼠标点击

**Comment by lanx214** [comment]
> 文档切换你用快捷键 还是鼠标点击

鼠标点击

**Comment by cumany** [comment]
新版本 再试试
