### ISSUE TITLE
是否可以自定义目录宽度

### ISSUE THREAD

**Issue by ribber** [cumany/obsidian-floating-toc-plugin#37]
目前标题太长时并且开启单行显示时，会显示省略号，如果标题的前缀相同并且很长，就无法区分标题。是否可以自定义宽度，或者自适应宽度，或者鼠标 hover 上去显示完整标题

**Comment by cumany** [comment]
已经支持 显示tooltip 这样不完整的标题 也可以有完整提示。
![image](https://user-images.githubusercontent.com/42957010/208736318-6bf650a7-e150-47f7-8ffd-28afbbd8fd43.png)
