### ISSUE TITLE
[FR] 能否使大纲自动缩进屏幕边界, 然后鼠标移至边界将之弹出显示

### ISSUE THREAD

**Issue by XMB-7** [cumany/obsidian-floating-toc-plugin#39]
目前我是将大纲停靠在屏幕右侧. 如果能让它自动收进去不显示, 然后鼠标挪移过去才触发将之唤出, (亦即始终保持pin状态的缩入与浮出), 那就更完美了. 
另外建议根据最长标题自适应调整大纲宽度(类似#37), 如图开启背景模糊, 可以看到, 即便标题很短, 大纲也占据了不小的宽度. 感谢.
![image](https://user-images.githubusercontent.com/65625632/203922089-168fd733-23e8-49e8-a103-d96903c6b0e1.png)

**Comment by cumany** [comment]
![image](https://user-images.githubusercontent.com/42957010/208736010-f6a93a27-85cd-4c74-9760-2c0d0de583cd.png)
调整指示条的位置 可以达到你的效果 比如调整到 -2.6
