### ISSUE TITLE
Console 'errors'

### ISSUE THREAD

**Issue by menagerie198** [cumany/obsidian-floating-toc-plugin#4]
First off -- many thanks for making this work. Love it. It is working fine for me in practice, but I am getting a lot of errors (in the hundreds this morning) reported in the 'inspector'. I'm not worried (I don’t know what they mean, and as I say, the plugin is doing what I want it to). I thought you might want to know about these things...
This is what I get in the console:
36 plugin:obsidian-floating-toc:6565 Uncaught TypeError: Cannot read properties of undefined (reading 'contains')
    at HTMLDocument._handleScroll (plugin:obsidian-floating-toc:6565:29)
    at s (app.js:1:265322)
    at l (app.js:1:265428)

**Comment by cumany** [comment]
fixed
