### ISSUE TITLE
能否在目录上加入文件目录或大纲里一样的层级竖线？

### ISSUE THREAD

**Issue by backkeys** [cumany/obsidian-floating-toc-plugin#40]
1.能否在目录上，加入文件目录或大纲里一样的层级竖线？这样看得更清晰。
2.以及Style Setting里对floating-toc的设置-外观设置-在指示条旁边显示标题上下级，开启后因为有的标题很长，很容易误触，导致一直打开floatingtoc的栏，能否使其显示出来的字碰到的情况下，不要打开floating-toc？
3.能否选择只显示到第几层标题？（有的时候小标题太多，目录过长）
![image](https://user-images.githubusercontent.com/119163748/204133092-fd37bf85-4af7-4e8f-a888-ed3e595379c8.png)
![image](https://user-images.githubusercontent.com/119163748/204133068-36076d5e-e485-4574-b42d-80c623f01431.png)

**Comment by wuzhen97** [comment]
不同标题层级之间的缩进太小啦，有时候很难区分各个层级之间的关系。希望大大能优化下

**Comment by cumany** [comment]
![image](https://user-images.githubusercontent.com/42957010/208735825-9785f94c-8aba-4eb7-999e-5f6b96b0f4ea.png)
新版本 已增加选项 并增加了标题的缩进距离
