### ISSUE TITLE
[Feature Request] Option to replace toc preview with toggle button

### ISSUE THREAD

**Issue by jsmorabito** [cumany/obsidian-floating-toc-plugin#41]
I would like the ability to hide the toc preview lines and instead show a button that toggles the floating toc:

TOC closed
<img width="276" alt="image" src="https://user-images.githubusercontent.com/46250921/204323797-58c3d96a-d40e-49c8-b2f3-67060edee6d8.png">

TOC button hovered
<img width="270" alt="image" src="https://user-images.githubusercontent.com/46250921/204323951-2082084e-b0fa-4c32-9250-b4f87021032a.png">

TOC open
<img width="462" alt="image" src="https://user-images.githubusercontent.com/46250921/204324010-404149b8-8535-4b9d-9692-05dde8aaa10e.png">

**Comment by DutchPete** [comment]
+1 I support that.

**Comment by cumany** [comment]
![image](https://user-images.githubusercontent.com/42957010/208735661-3a77b775-193b-41b8-8e0b-666ccb150b9e.png)
开启这个选项
