### ISSUE TITLE
Plugin isn't showing up in Style Settings

### ISSUE THREAD

**Issue by ReaderGuy42** [cumany/obsidian-floating-toc-plugin#42]
Hi, I'd like to change the color of the TOC, but the plugin isn't showing up in the style settings. I've turned both the plugin and style settings off and on again several times. 

Any ideas? thanks!

**Comment by cumany** [comment]
Turn on floating toc first, then turn on style settings
This way the style settings plugin will recognize the correct settings file.

**Comment by ReaderGuy42** [comment]
I did that, but it's still not showing up?

**Comment by BrommD** [comment]
I can approve, also not working for me (Windows10, Obsidian V1.10). Include follow up the upper proposal.
thx

**Comment by cumany** [comment]
![image](https://user-images.githubusercontent.com/42957010/208735326-ad8e5a05-69bd-47c9-ab07-4b42afdb95a9.png)
try to click this button  After updating version 2.3.0

**Comment by ReaderGuy42** [comment]
I've updated the plugin, turned both this plugin and Style Settings off and on again, and restarted Obsidian, but the plugin still isn't showing up in Style Settings.

**Comment by cumany** [comment]
This is quite strange
I added the open style setting setting to the floating toc, which is the same as adding insurance, and if it still doesn't work for you, I don't seem to know what to do

**Comment by ReaderGuy42** [comment]
that is weird. Oh well, this isn't that important. Thanks anyway :) If you happen to find a solution, you could comment again so I get notified.

**Comment by neuromaancer** [comment]
I have tried the default theme, it shows the options. I think it might be an issue for shimmering focus theme.
