### ISSUE TITLE
如何去掉 toc的 h1,h2 h3 标识？

### ISSUE THREAD

**Issue by Connor-yang96** [cumany/obsidian-floating-toc-plugin#44]
toc的 h1,h2 h3 标识 ，不太需要啊。怎么去掉啊。。。

**Comment by Connor-yang96** [comment]
css 里 自己改了。close。

**Comment by cumany** [comment]
![image](https://user-images.githubusercontent.com/42957010/208735096-c1ab1980-55d7-4b4f-a82b-eb7c69530e6d.png)
