### ISSUE TITLE
【FR】左窗口时，Toc在左边，右窗口时，TOC在右边。

### ISSUE THREAD

**Issue by Connor-yang96** [cumany/obsidian-floating-toc-plugin#45]
![image](https://user-images.githubusercontent.com/81000027/206849117-afd9248f-198f-4f53-84c9-1b112ed860c6.png)

这样看起来很舒服，操作也方便。

特别是右边窗口，TOC在左边的话，有点影响。虽然不太明显。
但这样 左窗口时，Toc在左边，右窗口时，TOC在右边。就很舒服了。

**Comment by cumany** [comment]
增加 both 位置选项
