### ISSUE TITLE
[Feature Request] Different colours for different headings

### ISSUE THREAD

**Issue by Sriramgireesh** [cumany/obsidian-floating-toc-plugin#46]
I know might be going overboard but if would be cool if it were possible to give distinct colours to different heading levels.

**Comment by cumany** [comment]
![image](https://user-images.githubusercontent.com/42957010/208734895-67f20013-27a6-4592-bde7-bbc4397b1b57.png)

**Comment by Sriramgireesh** [comment]
> ![image](https://user-images.githubusercontent.com/42957010/208734895-67f20013-27a6-4592-bde7-bbc4397b1b57.png)

Thank you so much
