### ISSUE TITLE
How to install the plugin ？能不能给个一步一步的安装指引？

### ISSUE THREAD

**Issue by jerrysoft-x** [cumany/obsidian-floating-toc-plugin#6]
我虽然知道应该把文件拷贝到plugins目录下面去，但是我实在不太明白在这里需要下载哪些文件，文件夹名字要叫什么。我的感觉大概是要先安装原来的插件，再从这里下载新的文件覆盖上去，到底对不对不知道没有说明现在只能靠猜。

**Comment by cumany** [comment]
两种安装方法 任选一种。

1.  brat 安装。插件目前还没有上架官方商店可以通过  [BRAT Plugin](https://obsidian.md/plugins?id=obsidian42-brat)去安装。
    `cumany/obsidian-floating-toc-plugin`

2.  所有的插件手动安装方法都是一样的，本插件也不例外。 
    在[releases](https://github.com/cumany/obsidian-floating-toc-plugin/releases) 下载 `main.js` `mainfest.json` `styles.css` 三个文件
    在Obsidian库目录下的 `.obsidian\plugins\` 新建一个插件目录名字`obsidian-floating-toc`文件夹。把刚才下载的三个文件放进去。
     ![](https://ghproxy.com/https://raw.githubusercontent.com/cumany/cumany/main/pic/202209221439471.png)
    最后在obsidian中开启本插件即可。
