### ISSUE TITLE
Feature 2 does not work properly

### ISSUE THREAD

**Issue by DutchPete** [cumany/obsidian-floating-toc-plugin#8]
Feature 2: The table of contents tracks the current scrolling position and highlights it synchronously

does not work properly:

![image](https://user-images.githubusercontent.com/10794265/191720972-2bf27200-e4db-4df4-ac29-5568d8678f41.png)

My cursor is at ### 4.6.1, whereas the highlight is at ## 4.5.

**Comment by cumany** [comment]
This highlighting does not track the cursor position, but the scrollbar. When a header scrolls into the current view range, it is highlighted. So this is an approximate range and not very exact.

**Comment by DutchPete** [comment]
I don't get it.

The highlighted header and the scrollbar are not at the same level. Furthermore, you say “when a header scrolls into the current view range, it is highlighted”, does not apply here.

The header that is highlighted in the ToC is in fact *out of view*. When I bring that header into the current view, the highlight moves to the next *out of view* header.

The way it is right now, this feature is more confusing than anything else.

**Comment by cumany** [comment]
Oh, I get it. It's a bug. I'll push a new update later.

**Comment by DutchPete** [comment]
Thanks. When you do, can you mention it here so I get a notification?

**Comment by cumany** [comment]
A new version has been released,.
You can click the watch button on top of github so that the plugin will send notifications when there is an action.

**Comment by DutchPete** [comment]
BTW, it has also started to behave like this:

![image](https://user-images.githubusercontent.com/10794265/191946673-a33c799e-573f-4fd3-9cf7-c98c74dfaec3.png)

**Comment by DutchPete** [comment]
OK, so 2.1.0 is the release that caused the jumbled text, because before it was not like that.

And the highlighted chapter in the ToC is still as before: offset from the scrollbar and the cursor.

**Comment by cumany** [comment]
Version 2.1.2 is released, try to see if there are still similar errors.

**Comment by DutchPete** [comment]
That was not a long wait; thanks for the quick response.

The text of the ToC is not jumbled anymore. However, the highlighting is the same as before: out of step with the scrollbar and cursor.

So, it now seems to me that, as per your earlier comment, the highlight should be seen as an approximate position of the cursor. In other words, it is not possible to get it to reflect the exact cursor position. If that is a correct statement we'll have to live with it.

**Comment by cumany** [comment]
Yes, highlighting is only related to scroll position, not to cursor position. When the header is scrolled within the view, highlighting is shown.

**Comment by cumany** [comment]
If you want to track the cursor position, it is theoretically possible to do so. It just needs some thinking about how to render it, because the cursor position does not change when scrolling, and getting the cursor position in real time consumes more resources. Does this have a big impact on the actual use, and is it worth the deep discussion?

**Comment by DutchPete** [comment]
> Does this have a big impact on the actual use, and is it worth the deep discussion?

No, and no. As far as I am concerned, #9 is a lot more important. For me the ToC is not practical with the tiny font size and without the possibility to change the colors.

I will close this issue.
