### ISSUE TITLE
2.4.1版本中设置右侧目录时，文本无法左对齐

### ISSUE THREAD

**Issue by fatsen** [cumany/obsidian-floating-toc-plugin#82]
2.4.1版本中，floating TOC position设置为right时，无论left alignment of TOC text是否勾选，文本都是右对齐。如下图。

![image](https://github.com/PKM-er/obsidian-floating-toc-plugin/assets/29320614/273015b0-8cc0-42d7-aa5b-0c5095d21cb4)

补充：
①2.4.1版本中，把鼠标悬浮到目录上方时，文本会变成左对齐；把鼠标移开，又会变成右对齐。
    关闭style setttings插件，行为不变。
    尝试打开style.css把所有的text-align改为right，无效。

②另一个库的2.3.0版本的插件，行为正常，无该问题。

**Comment by cumany** [comment]
下个版本修复
