### ISSUE TITLE
FR: offer the option to change the font size and color

### ISSUE THREAD

**Issue by DutchPete** [cumany/obsidian-floating-toc-plugin#9]
This is a very useful plug-in. Right now the font size is  small: 6px, if I am not mistaken. I tried to change it in the styles sheet but it does not work.

It would be useful to have an option to change the font size, perhaps via the *Style Settings* plug-in?

Also, my H1 has the accent color, my H2 has a different color, my H3-H6 have the text-normal color.

It would be useful to have the option to change to those colors in the floating ToC.

**Comment by PaulHerrero** [comment]
希望可以考虑通过支持 Settings Plugin 来修改目录样式

**Comment by cumany** [comment]
等0.16 发布后 会适配一些系统变量进去

**Comment by cumany** [comment]
![image](https://user-images.githubusercontent.com/42957010/192278533-d8f1d270-c48a-4273-b7f2-eb63c94b9807.png)
 已经支持

**Comment by DutchPete** [comment]
Yes!! Thank you so much, very good.
Is there a way to change the color for some headings, as per my OP, or is that too complicated? If it is complicated, leave it as it is, this is already pretty awesome.

**Comment by cumany** [comment]
I'm not sure if the 0.16 version of ob offers custom colors for header levels, I'd want to wait for the 0.16 release before making changes

**Comment by DutchPete** [comment]
In the core Outline plug-in it has been possible from the beginning. But let's wait for 0.16.
